from cvaugmentor.adapters.augmentations.blur import Blur
from cvaugmentor.adapters.augmentations.brightness import Brightness
from cvaugmentor.adapters.augmentations.cutout import Cutout
from cvaugmentor.adapters.augmentations.exposure import Exposure
from cvaugmentor.adapters.augmentations.flip import Flip
from cvaugmentor.adapters.augmentations.grayscale import Grayscale
from cvaugmentor.adapters.augmentations.hue import Hue
from cvaugmentor.adapters.augmentations.negative import Negative
from cvaugmentor.adapters.augmentations.no_augmentation import NoAugmentation
from cvaugmentor.adapters.augmentations.noise import Noise
from cvaugmentor.adapters.augmentations.rotate import Rotate
from cvaugmentor.adapters.augmentations.saturation import Saturation
from cvaugmentor.adapters.augmentations.shear import Shear
from cvaugmentor.adapters.augmentations.translation import Translation
from cvaugmentor.adapters.augmentations.zoom import Zoom
