name: Tests

on:
  push:
    paths:
      - 'CVAugmentor/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'CVAugmentor/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m unittest discover -s tests/
