name: Tests

on:
  push:
    paths:
      - 'CVAugmentor/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'CVAugmentor/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage codecov  # Install coverage and codecov

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests/ 
        coverage report  # Print coverage report
        coverage xml  # Create coverage XML report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2 
      with:
        file: ./coverage.xml
